AlexaSearch/Controllers/AlexaSearchIndexController.cs
using AlexaSearch.Models;
using Sitecore;
using Sitecore.ContentSearch;
using Sitecore.ContentSearch.Linq;
using Sitecore.ContentSearch.Linq.Utilities;
using Sitecore.Data.Items;
using Sitecore.Resources.Media;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Web;
using System.Web.Mvc;

namespace AlexaSearch.Controllers
{
    public class AlexaSearchIndexController : Controller
    {
        // GET: AlexaSearchIndex
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult DemoComponent()
        {
            var item = Sitecore.Context.Database.GetItem("{77AB5F36-B857-4845-B5B4-C044E0EA7F9B}");
            string str = item.Fields["Copyright"].Value;
            // Logic
            // Debugging - Being The Detective In a Crime Movie Where You Are Also The Murderer.
            return View("~/Views/Alexa/ControllerDemo.cshtml", item);
        }
        [HttpGet]
        public ActionResult blogbody()
        {
            List<Sitecore.Data.Items.Item> blogItems = new List<Sitecore.Data.Items.Item>();
            List<BlogModel> BlogCardsCollection = new List<BlogModel>();

            var itemm = Sitecore.Context.Database.GetItem("{F5BF3822-C8CC-47DA-BFA4-9C5CE6912BD3}");
            Sitecore.Data.Fields.MultilistField multilistField = itemm.Fields["PreferredArticles"];
            int len = multilistField.GetItems().Length;
            List<Sitecore.Data.Items.Item> items = new List<Item>();



            for (int i = 0; i < multilistField.GetItems().Length; i++)
            {

                blogItems.Add(multilistField.GetItems()[i]);
            }
            for (int i = 0; i < blogItems.Count; i++)
            {
                BlogModel BlogModel = new BlogModel();
                var imageUrl = string.Empty;

                Sitecore.Data.Fields.ImageField imageField = blogItems[i].Fields["BlogSmallImage"];
                if (imageField?.MediaItem != null)
                {
                    var image = new MediaItem(imageField.MediaItem);
                    imageUrl = StringUtil.EnsurePrefix('/', MediaManager.GetMediaUrl(image));
                    BlogModel.BlogSImage = imageUrl;
                }
                BlogModel.Category = blogItems[i].Fields["Category"].Value;
                BlogModel.BlogTitle = blogItems[i].Fields["Title"].Value;

                Sitecore.Data.Fields.DateField dateTimeField = blogItems[i].Fields["PostedDate"];

                string dateTimeString = dateTimeField.Value;

                DateTime dateTimeStruct = Sitecore.DateUtil.IsoDateToDateTime(dateTimeString);
                BlogModel.date = dateTimeStruct.ToShortDateString();

                BlogModel.ShortDesc = blogItems[i].Fields["ShortDescription"].Value;

                BlogModel.BlogURL = Sitecore.Links.LinkManager.GetItemUrl(blogItems[i]);
                BlogModel.sitecoreItem = blogItems[i];

                BlogCardsCollection.Add(BlogModel);
            }



            ViewBag.multi = BlogCardsCollection;
            return View("~/Views/Sitecoreblog/blogbody.cshtml");
        }



        //public ActionResult DemoComponent()
        //{
        //    var item = Sitecore.Context.Database.GetItem("/sitecore/content/Alexa/Home/Settings/GlobalSettings");

        //    return View("~/Views/Alexa/ControllerDemo.cshtml", item);
        //}
        [HttpPost]
        public ActionResult blogbody(FormCollection form)
        {
            string searchText = form["searchInput"];
            var myResults = new SearchResults
            {
                Results = new List<SearchResult>()
            };
            //var searchIndex = ContentSearchManager.GetIndex("sitecore_web_index"); // Get the search index
            //var searchPredicate = GetSearchPredicate(searchText); // Build the search predicate
            //using (var searchContext = searchIndex.CreateSearchContext()) // Get a context of the search index
            //{
            //    //Select * from Sitecore_web_index Where Author="searchText" OR Description="searchText" OR Title="searchText"
            //    //var searchResults = searchContext.GetQueryable<SearchModel>().Where(searchPredicate); // Search the index for items which match the predicate
            //    var searchResults = searchContext.GetQueryable<SearchModel>()
            //        .Where(x => x.Author.Contains(searchText) || x.Title.Contains(searchText) || x.Description.Contains(searchText));   //LINQ query

            //    var fullResults = searchResults.GetResults();

            //    // This is better and will get paged results - page 1 with 10 results per page
            //    //var pagedResults = searchResults.Page(1, 10).GetResults();
            //    foreach (var hit in fullResults.Hits)
            //    {
            //        myResults.Results.Add(new SearchResult
            //        {
            //            Description = hit.Document.Description,
            //            Title = hit.Document.Title,
            //            ItemName = hit.Document.ItemName,
            //            Author = hit.Document.Author
            //        });
            //    }
            //    return new JsonResult { JsonRequestBehavior = JsonRequestBehavior.AllowGet, Data = myResults };



            //Sitecore.Data.Database master = Sitecore.Configuration.Factory.GetDatabase("web");



            List<string> solr = new List<string>();
            List<string> itemsss = new List<string>();
            List<Sitecore.Data.Items.Item> blogItems = new List<Sitecore.Data.Items.Item>();

            var itemm = Sitecore.Context.Database.GetItem("{F5BF3822-C8CC-47DA-BFA4-9C5CE6912BD3}");
            Sitecore.Data.Fields.MultilistField multilistField = itemm.Fields["PreferredArticles"];
            if (multilistField != null)
            {
                foreach (Sitecore.Data.Items.Item city in multilistField.GetItems())
                {
                    blogItems.Add(city);
                }
            }

            //var searchIndex = ContentSearchManager.GetIndex("sitecore_web_index"); // Get the search index
            //var searchPredicate = GetSearchPredicate(searchText); // Build the search predicate
            //using (var searchContext = searchIndex.CreateSearchContext()) // Get a context of the search index
            //{
            //    //Select * from Sitecore_web_index Where Author="searchText" OR Description="searchText" OR Title="searchText"
            //    //var searchResults = searchContext.GetQueryable<SearchModel>().Where(searchPredicate); // Search the index for items which match the predicate
            //    var searchResults = searchContext.GetQueryable<SearchModel>()
            //        .Where(x => x.Title.Contains(searchText) );   //LINQ query

            //    var fullResults = searchResults.GetResults();

            //    // This is better and will get paged results - page 1 with 10 results per page
            //    //var pagedResults = searchResults.Page(1, 10).GetResults();
            //    foreach (var hit in fullResults.Hits)
            //    {
            //        myResults.Results.Add(new SearchResult
            //        {
            //            Description = hit.Document.Description,
            //            Title = hit.Document.Title,
            //            ItemName = hit.Document.ItemName,
            //            Author = hit.Document.Author
            //        });
            //        solr.Add(System.Convert.ToString(hit.Document.ItemId));

            //    }
            //    
            //    List<string> res = new List<string>();

            //    foreach (string i in itemsss)
            //    {
            //        if (solr.Contains(i))
            //        {

            //            res.Add(i);

            //        }
            //    }
            //    int len = res.Count;
            //    List<Sitecore.Data.Items.Item> items = new  List<Item>();

            //    for (int j = 0; j < res.Count; j++)
            //    {
            //        Sitecore.Data.Items.Item item1 = Sitecore.Context.Database.GetItem(res[j]);
            //        items.Add(item1);
            //    }


               List<BlogModel> BlogCardsCollection = new List<BlogModel>();

            for (int i = 0; i < multilistField.GetItems().Length; i++)
                {
                    BlogModel BlogModel = new BlogModel();
                    var imageUrl = string.Empty;

                    
                    BlogModel.Category = blogItems[i].Fields["Category"].Value;
                    BlogModel.BlogTitle = blogItems[i].Fields["Title"].Value;

                    Sitecore.Data.Fields.DateField dateTimeField = blogItems[i].Fields["PostedDate"];

                    string dateTimeString = dateTimeField.Value;

                    DateTime dateTimeStruct = Sitecore.DateUtil.IsoDateToDateTime(dateTimeString);
                    BlogModel.date = dateTimeStruct.ToShortDateString();

                    BlogModel.ShortDesc = blogItems[i].Fields["LongDescription"].Value;

                    BlogModel.BlogURL = Sitecore.Links.LinkManager.GetItemUrl(blogItems[i]);
                    BlogModel.sitecoreItem = blogItems[i];

                    BlogCardsCollection.Add(BlogModel);
                }

           

                List<BlogModel> results = BlogCardsCollection.FindAll(Findtitle);



                bool Findtitle(BlogModel bk)
                {

                    if (bk.BlogTitle.Contains(searchText) || bk.Category.Contains(searchText) || bk.ShortDesc.Contains(searchText) )
                    {
                        return true;
                    }
                    else
                    {
                        return false;
                    }
                }

                ViewBag.multi = results;

AlexaSearch/Views/Alexa/ArticleBody.cshtml
<div>
			<h1>@Html.Sitecore().Field("title") </h1>
			<h4>@Html.Sitecore().Field("BlogId")</h4>
			<h4>@Html.Sitecore().Field("description")</h4>
			<h4>@Html.Sitecore().Field("author")</h4>
			<h4>@Html.Sitecore().Field("authorwikilink")</h4>
			<h4>@Html.Sitecore().Field("posteddate")</h4>
			<h4>@Html.Sitecore().Field("blogimage")</h4>
		</div>

AlexaSearch/Views/Alexa/ControllerDemo.cshtml
@model Sitecore.Data.Items.Item

<div>
    Way 1 - @Model["WebsiteHeading"]
    <br />
    Way 2 - @Model.Fields["WebsiteHeading"].Value
    <br />
    Way 3 - @Html.Sitecore().Field("WebsiteHeading", Model)
    <br />
    Way 4 - @Html.Raw(Model.Fields["WebsiteHeading"].Value)
</div>

AlexaSearch/Views/Alexa/DefaultLayout.cshtml
@using Sitecore.Mvc
@using Sitecore.Mvc.Analytics.Extensions
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
    <body>
<div>
			<p>===============================================================================</p><br>
			This is my Header Component<br>
			<p>===============================================================================</p><br>
		</div>	
        <div>
			<h1>@Html.Sitecore().Field("Title") </h1>
			<h4>@Html.Sitecore().Field("Blogid")</h4>
			<h4>@Html.Sitecore().Field("description")</h4>
			<h4>@Html.Sitecore().Field("author")</h4>
			<h4>@Html.Sitecore().Field("authorwikilink")</h4>
			<h4>@Html.Sitecore().Field("posteddate")</h4>
			<h4>@Html.Sitecore().Field("blogimage")</h4>
		</div>
<div>
			<p>===============================================================================</p><br>
			This is my Footer Component<br>
			<p>===============================================================================</p><br>
		</div>		
    </body>
	<div>
            @Html.Sitecore().Placeholder("phMain")
        </div>
</html>

AlexaSearch/Views/Alexa/DefaultMaster.cshtml
<html>
<body>
<h1>welcome to sitecore</h1>
</body>
</html>

AlexaSearch/Views/Alexa/Footer.cshtml
	
		@{
    var item = Sitecore.Context.Database.GetItem("/sitecore/content/Home/Alexa/websiteSettings/localsetting");
    //var item = Sitecore.Context.Database.GetItem("{{{{77AB5F36-B857-4845-B5B4-C044E0EA7F9B}}}");
}
	
    <div>
        
         @Html.Raw( item.Fields["copyright"].Value)
    </div>

AlexaSearch/Views/Alexa/Header.cshtml
	
		@{
    var item = Sitecore.Context.Database.GetItem("/sitecore/content/Home/Alexa/websiteSettings/localsetting");
    //var item = Sitecore.Context.Database.GetItem("{{{{77AB5F36-B857-4845-B5B4-C044E0EA7F9B}}}");
}
	
    <div>
        
         @Html.Raw( item.Fields["websiteheading"].Value)
    </div>

AlexaSearch/Views/Alexa/Search.cshtml
@{
    ViewBag.Title = "SOLR Search Component";
}

<h2>Search Item</h2>
<div class="form-example">
    <label for="name">Search Item </label>
    <input type="text" name="name" id="searchInput" required>
</div>
<br />
<br />

<div class="form-example">
    <button class="favorite styled" type="button" id="searchButton">
        Search
    </button>
</div>

<div id="resultsItem"></div>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
<script>
		$(document).ready(function () {
			$("#searchButton").click(function (e) {
				// debugger;
				e.preventDefault();
				$.ajax({
					type: "GET",
					datatype: "JSON", url: "@Url.Action("DoSearch", "AlexaSearchIndex")",
					contentType: "application/json",
					data: {
						searchText: $("#searchInput").val()
					},
					success: function (result) {
						var resultText = "";
						$('#resultsItem').text(resultText);
						$('#resultsItem').append("Results from SOLR index <BR><BR>");
						$(result.Results).each(function (index, item) {
							// each iteration
							var Description = item.Description;
							var Title = item.Title;
							var Author = item.Author;
							var ItemName = item.ItemName;
							resultText += (index + 1) + " - " + ItemName + Title + "; " + Author + "; " + Description + "; " + "<BR><BR>";
						});
						$('#resultsItem').append(resultText);
					},
					error: function (result) {
						alert('error');
					}
				});
			});
		});
</script>